version: 2

models:
  - name: fact_usage_stats
    description: ""
    columns:
      - name: rental_id
        data_type: string
        description: ""

      - name: duration
        data_type: int64
        description: ""

      - name: bike_id
        data_type: string
        description: ""

      - name: end_date
        data_type: datetime
        description: ""

      - name: endstation_id
        data_type: string
        description: ""

      - name: endstation_name
        data_type: string
        description: ""

      - name: start_date
        data_type: datetime
        description: ""

      - name: startstation_id
        data_type: string
        description: ""

      - name: startstation_name
        data_type: string
        description: ""

  - name: fact_activetravelcountsprogramme
    description: ""
    columns:
      - name: wave
        data_type: string
        description: ""

      - name: site_id
        data_type: string
        description: ""

      - name: date
        data_type: date
        description: ""

      - name: weather
        data_type: string
        description: ""

      - name: time
        data_type: time
        description: ""

      - name: day
        data_type: string
        description: ""

      - name: round
        data_type: string
        description: ""

      - name: direction
        data_type: string
        description: ""

      - name: path
        data_type: string
        description: ""

      - name: mode
        data_type: string
        description: ""

      - name: count
        data_type: int64
        description: ""

  - name: dim_locations
    description: ""
    columns:
      - name: site_id
        data_type: string
        description: ""

      - name: description
        data_type: string
        description: ""

      - name: borough
        data_type: string
        description: ""

      - name: functional_area
        data_type: string
        description: ""

      - name: road type
        data_type: string
        description: ""

      - name: is_strategic_cio
        data_type: int64
        description: ""

      - name: old_site_id
        data_type: string
        description: ""

      - name: easting
        data_type: float64
        description: ""

      - name: northing
        data_type: float64
        description: ""

      - name: latitude
        data_type: float64
        description: ""

      - name: longitude
        data_type: float64
        description: ""