name: Airflow CI (Docker)

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker image
        run: |
          docker build -t my-airflow:ci-test ./airflow

      - name: Install Docker Compose
        run: |
          sudo curl -L "https://github.com/docker/compose/releases/download/1.29.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
          sudo chmod +x /usr/local/bin/docker-compose
          docker-compose --version  # Verify installation

                    
      - name: Start Docker container
        run: |
            docker-compose -f airflow/docker-compose.yaml up -d  # Assuming you're using docker-compose, this starts the containers in the background


      - name: Run tests inside the container
        run: |
                docker-compose exec airflow-webserver bash -c "pytest tests/"

      - name: Stop Docker container
        run: |
                docker-compose down  # Stop and remove the containers after tests