name: Airflow Code Quality Check

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  quality:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'  # or 3.8, 3.10 depending on your Airflow version

      - name: Install minimal requirements
        run: |
          pip install apache-airflow==2.6.1  # match your Airflow version
          pip install flake8 pytest

      - name: Lint code with flake8
        run: |
          flake8 dags/ tests/  # or wherever your code is

      - name: Test DAG loading (DAG integrity test)
        run: |
          python scripts/check_dags.py